export const rusheeList = 
 [{'_id': '5d707a675189393c5b6f654',
  'meta': {'stage': 2},
  'personal': {'first_name': 'Abigail',
   'last_name': 'Stautberg',
   'gender': 'female',
   'email': 'astautbe@umich.edu',
   'phone_number': '(513) 335-2461',
   'dorm_number': '22',
   'dorm_name': 'Kappa Kappa Gamma',
   'address_type': 'on_campus',
   'prior_rush': 'no'},
  'files': {'transcript_original_name': 'SSR_TSRPT_SC.pdf',
   'transcript_stored_location': '/rush_w19/rushee_data/user_5d707a675189393c5b6f654d/transcript_Yqcg7rN18FjAX70MdHrALACu.pdf',
   'picture_original_name': 'rsz_1p1280721.jpg',
   'picture_stored_location': '/rush_w19/rushee_data/user_5d707a675189393c5b6f654d/photo_9cwUSZGAIDLrw4uez63fV6Dk.jpg'},
  'academics': {'high_school': {'hs_name': 'Saint Ursula Academy',
    'hs_location': 'Cincinnati, Ohio',
    'hs_grad_year': '2018',
    'hs_gpa': '3.9',
    'hs_gpa_max': '4.0'},
   'majors': 'Aerospace Engineering',
   'um_gpa': '3.76',
   'act': '33',
   'um_grad_sem': 'w_22',
   'school/college': 'Engineering',
   'transfer': 'no'},
  'shortanswer': {'q1': 'For the rest of my undergraduate career, my classmates and I will share comparable aspirations such as walking on Mars, developing autonomous, solar powered aircraft, and constructing rockets, however I want to be a part of a larger community whose interests span the spectrum of everything from computer science to business, and I have found that inclusivity within AKPsi. The unique facets of each brother’s persona feed into the omnipresent collaborative and close-knit environment, which I believe will allow me the opportunity to become well-versed in a broad range of topics, thereby easing my entrance into the aerospace engineering industry.\nWhen surrounded by the brotherhood, I can feel the drive and hustle from each person, inspiring determination amid the group. Thriving amongst individuals who push me to work harder, I want to take part in this ambitious atmosphere while motivating others to persevere in accomplishing their goals.\n',
   'q2': 'If I was on the cover of a magazine it would be SpaceNews magazine, spotlighting my triumph as the first human to reach an exoplanet. It would explain how I began my research and testing through participation in a Life Detection Conference–centered on advancing microscopy to better document microbes for the Mars Mission–which supplemented my pre-existing interest in the field and taught me how to effectively recognize and record foreign life-forms. Once confirming habitability, the article describes the design and manufacturing process, along with the eventual arrival and revolutionary landing. This achievement is my life’s chief goal, as I’ve always dreamt of sending CubeSats to exoplanets and perform breakthrough research in the astronautical domain. Ultimately, this magazine would feature me not just for establishing a new civilization on an unfamiliar planet, but for my influential leadership in the space industry, inspiring others to persist in the exploration of the unknown.',
   'q3': 'In this production, I would act as casting director on account of my ability to evaluate people’s strengths and weaknesses, further sorting them into positions that best suit their capacities. By working in the food and customer service industries, I have become proficient in reading and assessing people based off their demeanor, while additionally developing valuable interpersonal skills. Further, as an engineer, I’m adept at finding solutions to uniquely challenging problems. In the position of casting director, I would utilize my analytical mindset to assign those I am casting the roles for which they would flourish in. '},
  'resume': {'experiences': [{'activity_name': 'Sotto Restaurant',
     'activity_position': 'Server Assistant/Hostess',
     'date_start': '05/10/2018',
     'date_end': '08/15/2019',
     'activity_description': 'Hostess:\n* organizing the seating arrangements\n* attending to guests\n* aiding managers with supplemental tasks\n\nServer Assistant:\n* presenting and describing dishes to the guests\n* assisting the food expeditor\n* attending to the needs of the tables',
     'hours_week': '35'},
    {'activity_name': 'Anthropologie and Urban Outfitters',
     'activity_position': 'Customer Associate ',
     'date_start': '05/04/2019',
     'date_end': '09/05/2019',
     'activity_description': '* consulted customers in fashioning statement outfits\n* undertook initiatives in response to situations occurring in the store',
     'hours_week': '15'},
    {'activity_name': 'Michigan Mars Rover Team',
     'activity_position': 'Member of the Hardware Interface Team',
     'date_start': '09/12/2018',
     'date_end': '04/18/2019',
     'activity_description': '* Collaborated with others to rewrite the onboard program and other low-level code\n* programmed new features for the rover to operate more efficiently with the goal of winning the University Rover Challenge',
     'hours_week': '15'},
    {'activity_name': 'Imaging for Life Detection Conference',
     'activity_position': 'Participant',
     'date_start': '08/28/2019',
     'date_end': '08/30/2019',
     'activity_description': '* shared my ideas and concerns about our current technology used for microbial detection\n* brainstormed new solutions to revolutionize our instruments used to detect and image life alongside leaders in their fields with the result being a published journal article\n* raised awareness for the need for a solution for this pressing matter as the Mars mission is underway',
     'hours_week': '24'}],
   'work_experience': "Sotto Restaurant: Server Assistant/Hostess\nAnthropologie: Customer Associate\nUrban Outfitters: Customer Associate\nGraeter's Ice Cream: Team Member\nYMCA Camp Ernst: Counselor\nBabysitting",
   'clubs_and_sports': 'Michigan Mars Rover Team: Hardware Interface Team Member\nStudent Space Systems Fabrication Lab: BlueSat Team Member\nKappa Kappa Gamma Sorority\nYMCA Camp Ernst Junior Board\nBulldog Buddies Tutoring\nSocial Justice Club and Mission Collection\nSaint Ursula Academy Ambassador\nHigh School and Club Soccer\nHigh School Cross Country',
   'community_service': 'Reading is Fundamental\nBulldog Buddies Tutoring\nSocial Justice Club and Mission Collection\nPersonal Care Drive Facilitator',
   'honors_and_awards': 'University Honors\nNational Honor Society\nNational Latin Exam, Cum Laude\nFirst Honors\nScholar Athlete'},
  'rr': {'sen': {'score': 8.0,
    'status': 2,
    'bro_id': '5d771d1a7c819be63c6699f1',
    'scores': [{'id': 'crit1', 'value': 3},
     {'id': 'crit2', 'value': 2},
     {'id': 'crit3', 'value': 3},
     {'id': 'crit4', 'value': 3},
     {'id': 'crit5', 'value': 4}]},
   'jun': {'score': 8.0,
    'status': 2,
    'bro_id': '5d82dbdc4cf4683e83bd01cd',
    'scores': [{'id': 'crit1', 'value': 4},
     {'id': 'crit2', 'value': 2},
     {'id': 'crit3', 'value': 3},
     {'id': 'crit4', 'value': 2},
     {'id': 'crit5', 'value': 4}]},
   'soph': {'score': 8.0,
    'status': 2,
    'bro_id': '5d771d1a7c819be63c6699f1',
    'scores': [{'id': 'crit1', 'value': 3},
     {'id': 'crit2', 'value': 3},
     {'id': 'crit3', 'value': 3},
     {'id': 'crit4', 'value': 3},
     {'id': 'crit5', 'value': 3}]}},
  't50': 3,
  'bhs': [{'brother_id': '5d89a17b076505d47e8e3c62',
    'professional_score': 6,
    'social_score': 8,
    'comment': 'Easy to talk to, has a lot of impressive fun facts',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d78777ccaecf5b7f1808700',
    'professional_score': 6,
    'social_score': 7,
    'comment': 'Responded with solid points when I asked about her reasons for pursuing aerospace and her interest in AKPsi. Was very interested in meeting Jon who I said was also in the major. At coffee chats, my conversation with Abigail stood out from the rest of the generic conversations.',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': true},
    'weight': 60},
   {'brother_id': '5d82e2e4f2f656139d9323e5',
    'professional_score': 7,
    'social_score': 5,
    'comment': '',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d8a762d312de3dfe705af12',
    'professional_score': 7,
    'social_score': 7,
    'comment': '',
    'encounters': {'pre_t50': false, 'speed_dating': true, 't50': false},
    'weight': 50},
   {'brother_id': '5d813e31977cd4b41c415859',
    'professional_score': 6,
    'social_score': 8,
    'comment': 'Abigail and I spoke at rush bbq and had a great conversation. We were in a group of many different people and she didn’t struggle standing out at all. She was great to talk to and really knowledgeable on what we were talking about. I am confident she would be a great addition to this brotherhood\n',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 60},
   {'brother_id': '5d82c0d956604c6b785cba90',
    'professional_score': 4,
    'social_score': 4,
    'comment': 'hard to connect with during top 50. Was vert quiet and stoic',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d814f5fd0dc9571e267fa98',
    'professional_score': 5,
    'social_score': 7,
    'comment': '',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 50},
   {'brother_id': '5d8b8839cb8d366c05b3959e',
    'professional_score': 6,
    'social_score': 4,
    'comment': '',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 50},
   {'brother_id': '5d8b9e88cb8d366c05b3959f',
    'professional_score': 3,
    'social_score': 5,
    'comment': "said she was interested in space but hadn't heard of the black hole being photographed this year, which was biggest space news of the year? makes me question if she's actually interested because once she was pushed on her unique interest at all she had nothing to back it up",
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d705587b47f6bd85140115f',
    'professional_score': 5,
    'social_score': 4,
    'comment': '',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 50},
   {'brother_id': '5d8bb077cb8d366c05b395a1',
    'professional_score': 9,
    'social_score': 9,
    'comment': 'One of my favorite conversations at top 50 reception, she just clearly was passionate about everything she spoke about, including her interest in joining akpsi',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d8a3124076505d47e8e3c64',
    'professional_score': 5,
    'social_score': 10,
    'comment': '',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d82dbdc4cf4683e83bd01cd',
    'professional_score': 3,
    'social_score': 4,
    'comment': 'She was not engaging in conversation and dry to talk to, Sabina also asked her about things in space ',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d831230a051ef6e3d9f9929',
    'professional_score': 4,
    'social_score': 5,
    'comment': 'Abigail seems really sweet but during the two events I talked to her at before Top 50, she just seemed bored. She didnt seem engaged or interested in the conversations we were having. She also was completely disengaged when other people within the group were talking despite them giving their attention to her when she was talking.',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 50},
   {'brother_id': '5d83d4b12be2dff7a8c86b39',
    'professional_score': 2,
    'social_score': 2,
    'comment': 'First impression was not great, she made a few unprofessional comments about pledging that she had heard about (having to pull all-nighters in the library, never sleeping, etc that I am guessing she heard from other brothers so not holding it too much against her). In general though hard to talk to, I had to push a conversation along. Could be shyness, but came off as though she was uninterested.',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d83e931a051ef6e3d9f992c',
    'professional_score': 6,
    'social_score': 6,
    'comment': '',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': false},
    'weight': 50}],
  'gi': [{'brother_name': 'John Gearig',
    'score': 12,
    'decision': 'No w/ Reserves',
    'comments': '-logical and non-dominant\n-decent communicating'},
   {'brother_name': 'Annika',
    'score': 8,
    'decision': 'No',
    'comments': "-writing on board not really adding ideas or commentary\n-not a lot of enthusiasm in her presentation\n-wasn't looking at others while they spoke"}],
  'ii': [{'brother_name': 'Audrey Humphrey ',
    'score': 12.75,
    'decision': 'Yes w/ Reserves',
    'comments': '-yes with reserves but could be no with reserves, v on the fence\n-got better at the end when she apoke about her aerospace engineering interests, through her overall tone was  monotone, and she had to be pressed on most questions'},
   {'brother_name': 'Sinan Karabocuoglu',
    'score': 14.25,
    'decision': 'Yes w/ Reserves',
    'comments': "-she is very interestedin the field and knowledgable\n-she was a monotone and doesn't try hard on challenging questions\n-she didnt ask any questions at the end "},
   {'brother_name': 'Arjun Vivek',
    'score': 12.5,
    'decision': 'Yes w/ Reserves',
    'comments': 'LACKS CONFIDENCE AND EXPERIENE\n\n-Unique way of thinking'}],
  'vm2': {'curr_rank': 1, 'locked': false, 'strike': false}},
  {'_id': '5d707a675189393c5b6f654dfr',
  'meta': {'stage': 2},
  'personal': {'first_name': 'Abigail2',
   'last_name': 'Stautberg2',
   'gender': 'female',
   'email': 'astautbe@umich.edu',
   'phone_number': '(513) 335-2461',
   'dorm_number': '22',
   'dorm_name': 'Kappa Kappa Gamma',
   'address_type': 'on_campus',
   'prior_rush': 'no'},
  'files': {'transcript_original_name': 'SSR_TSRPT_SC.pdf',
   'transcript_stored_location': '/rush_w19/rushee_data/user_5d707a675189393c5b6f654d/transcript_Yqcg7rN18FjAX70MdHrALACu.pdf',
   'picture_original_name': 'rsz_1p1280721.jpg',
   'picture_stored_location': '/rush_w19/rushee_data/user_5d707a675189393c5b6f654d/photo_9cwUSZGAIDLrw4uez63fV6Dk.jpg'},
  'academics': {'high_school': {'hs_name': 'Saint Ursula Academy',
    'hs_location': 'Cincinnati, Ohio',
    'hs_grad_year': '2018',
    'hs_gpa': '3.9',
    'hs_gpa_max': '4.0'},
   'majors': 'Aerospace Engineering',
   'um_gpa': '3.76',
   'act': '33',
   'um_grad_sem': 'w_22',
   'school/college': 'Engineering',
   'transfer': 'no'},
  'shortanswer': {'q1': 'For the rest of my undergraduate career, my classmates and I will share comparable aspirations such as walking on Mars, developing autonomous, solar powered aircraft, and constructing rockets, however I want to be a part of a larger community whose interests span the spectrum of everything from computer science to business, and I have found that inclusivity within AKPsi. The unique facets of each brother’s persona feed into the omnipresent collaborative and close-knit environment, which I believe will allow me the opportunity to become well-versed in a broad range of topics, thereby easing my entrance into the aerospace engineering industry.\nWhen surrounded by the brotherhood, I can feel the drive and hustle from each person, inspiring determination amid the group. Thriving amongst individuals who push me to work harder, I want to take part in this ambitious atmosphere while motivating others to persevere in accomplishing their goals.\n',
   'q2': 'If I was on the cover of a magazine it would be SpaceNews magazine, spotlighting my triumph as the first human to reach an exoplanet. It would explain how I began my research and testing through participation in a Life Detection Conference–centered on advancing microscopy to better document microbes for the Mars Mission–which supplemented my pre-existing interest in the field and taught me how to effectively recognize and record foreign life-forms. Once confirming habitability, the article describes the design and manufacturing process, along with the eventual arrival and revolutionary landing. This achievement is my life’s chief goal, as I’ve always dreamt of sending CubeSats to exoplanets and perform breakthrough research in the astronautical domain. Ultimately, this magazine would feature me not just for establishing a new civilization on an unfamiliar planet, but for my influential leadership in the space industry, inspiring others to persist in the exploration of the unknown.',
   'q3': 'In this production, I would act as casting director on account of my ability to evaluate people’s strengths and weaknesses, further sorting them into positions that best suit their capacities. By working in the food and customer service industries, I have become proficient in reading and assessing people based off their demeanor, while additionally developing valuable interpersonal skills. Further, as an engineer, I’m adept at finding solutions to uniquely challenging problems. In the position of casting director, I would utilize my analytical mindset to assign those I am casting the roles for which they would flourish in. '},
  'resume': {'experiences': [{'activity_name': 'Sotto Restaurant',
     'activity_position': 'Server Assistant/Hostess',
     'date_start': '05/10/2018',
     'date_end': '08/15/2019',
     'activity_description': 'Hostess:\n* organizing the seating arrangements\n* attending to guests\n* aiding managers with supplemental tasks\n\nServer Assistant:\n* presenting and describing dishes to the guests\n* assisting the food expeditor\n* attending to the needs of the tables',
     'hours_week': '35'},
    {'activity_name': 'Anthropologie and Urban Outfitters',
     'activity_position': 'Customer Associate ',
     'date_start': '05/04/2019',
     'date_end': '09/05/2019',
     'activity_description': '* consulted customers in fashioning statement outfits\n* undertook initiatives in response to situations occurring in the store',
     'hours_week': '15'},
    {'activity_name': 'Michigan Mars Rover Team',
     'activity_position': 'Member of the Hardware Interface Team',
     'date_start': '09/12/2018',
     'date_end': '04/18/2019',
     'activity_description': '* Collaborated with others to rewrite the onboard program and other low-level code\n* programmed new features for the rover to operate more efficiently with the goal of winning the University Rover Challenge',
     'hours_week': '15'},
    {'activity_name': 'Imaging for Life Detection Conference',
     'activity_position': 'Participant',
     'date_start': '08/28/2019',
     'date_end': '08/30/2019',
     'activity_description': '* shared my ideas and concerns about our current technology used for microbial detection\n* brainstormed new solutions to revolutionize our instruments used to detect and image life alongside leaders in their fields with the result being a published journal article\n* raised awareness for the need for a solution for this pressing matter as the Mars mission is underway',
     'hours_week': '24'}],
   'work_experience': "Sotto Restaurant: Server Assistant/Hostess\nAnthropologie: Customer Associate\nUrban Outfitters: Customer Associate\nGraeter's Ice Cream: Team Member\nYMCA Camp Ernst: Counselor\nBabysitting",
   'clubs_and_sports': 'Michigan Mars Rover Team: Hardware Interface Team Member\nStudent Space Systems Fabrication Lab: BlueSat Team Member\nKappa Kappa Gamma Sorority\nYMCA Camp Ernst Junior Board\nBulldog Buddies Tutoring\nSocial Justice Club and Mission Collection\nSaint Ursula Academy Ambassador\nHigh School and Club Soccer\nHigh School Cross Country',
   'community_service': 'Reading is Fundamental\nBulldog Buddies Tutoring\nSocial Justice Club and Mission Collection\nPersonal Care Drive Facilitator',
   'honors_and_awards': 'University Honors\nNational Honor Society\nNational Latin Exam, Cum Laude\nFirst Honors\nScholar Athlete'},
  'rr': {'sen': {'score': 8.0,
    'status': 2,
    'bro_id': '5d771d1a7c819be63c6699f1',
    'scores': [{'id': 'crit1', 'value': 3},
     {'id': 'crit2', 'value': 2},
     {'id': 'crit3', 'value': 3},
     {'id': 'crit4', 'value': 3},
     {'id': 'crit5', 'value': 4}]},
   'jun': {'score': 8.0,
    'status': 2,
    'bro_id': '5d82dbdc4cf4683e83bd01cd',
    'scores': [{'id': 'crit1', 'value': 4},
     {'id': 'crit2', 'value': 2},
     {'id': 'crit3', 'value': 3},
     {'id': 'crit4', 'value': 2},
     {'id': 'crit5', 'value': 4}]},
   'soph': {'score': 8.0,
    'status': 2,
    'bro_id': '5d771d1a7c819be63c6699f1',
    'scores': [{'id': 'crit1', 'value': 3},
     {'id': 'crit2', 'value': 3},
     {'id': 'crit3', 'value': 3},
     {'id': 'crit4', 'value': 3},
     {'id': 'crit5', 'value': 3}]}},
  't50': 3,
  'bhs': [{'brother_id': '5d89a17b076505d47e8e3c62',
    'professional_score': 6,
    'social_score': 8,
    'comment': 'Easy to talk to, has a lot of impressive fun facts',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d78777ccaecf5b7f1808700',
    'professional_score': 6,
    'social_score': 7,
    'comment': 'Responded with solid points when I asked about her reasons for pursuing aerospace and her interest in AKPsi. Was very interested in meeting Jon who I said was also in the major. At coffee chats, my conversation with Abigail stood out from the rest of the generic conversations.',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': true},
    'weight': 60},
   {'brother_id': '5d82e2e4f2f656139d9323e5',
    'professional_score': 7,
    'social_score': 5,
    'comment': '',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d8a762d312de3dfe705af12',
    'professional_score': 7,
    'social_score': 7,
    'comment': '',
    'encounters': {'pre_t50': false, 'speed_dating': true, 't50': false},
    'weight': 50},
   {'brother_id': '5d813e31977cd4b41c415859',
    'professional_score': 6,
    'social_score': 8,
    'comment': 'Abigail and I spoke at rush bbq and had a great conversation. We were in a group of many different people and she didn’t struggle standing out at all. She was great to talk to and really knowledgeable on what we were talking about. I am confident she would be a great addition to this brotherhood\n',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 60},
   {'brother_id': '5d82c0d956604c6b785cba90',
    'professional_score': 4,
    'social_score': 4,
    'comment': 'hard to connect with during top 50. Was vert quiet and stoic',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d814f5fd0dc9571e267fa98',
    'professional_score': 5,
    'social_score': 7,
    'comment': '',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 50},
   {'brother_id': '5d8b8839cb8d366c05b3959e',
    'professional_score': 6,
    'social_score': 4,
    'comment': '',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 50},
   {'brother_id': '5d8b9e88cb8d366c05b3959f',
    'professional_score': 3,
    'social_score': 5,
    'comment': "said she was interested in space but hadn't heard of the black hole being photographed this year, which was biggest space news of the year? makes me question if she's actually interested because once she was pushed on her unique interest at all she had nothing to back it up",
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d705587b47f6bd85140115f',
    'professional_score': 5,
    'social_score': 4,
    'comment': '',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 50},
   {'brother_id': '5d8bb077cb8d366c05b395a1',
    'professional_score': 9,
    'social_score': 9,
    'comment': 'One of my favorite conversations at top 50 reception, she just clearly was passionate about everything she spoke about, including her interest in joining akpsi',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d8a3124076505d47e8e3c64',
    'professional_score': 5,
    'social_score': 10,
    'comment': '',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d82dbdc4cf4683e83bd01cd',
    'professional_score': 3,
    'social_score': 4,
    'comment': 'She was not engaging in conversation and dry to talk to, Sabina also asked her about things in space ',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d831230a051ef6e3d9f9929',
    'professional_score': 4,
    'social_score': 5,
    'comment': 'Abigail seems really sweet but during the two events I talked to her at before Top 50, she just seemed bored. She didnt seem engaged or interested in the conversations we were having. She also was completely disengaged when other people within the group were talking despite them giving their attention to her when she was talking.',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': false},
    'weight': 50},
   {'brother_id': '5d83d4b12be2dff7a8c86b39',
    'professional_score': 2,
    'social_score': 2,
    'comment': 'First impression was not great, she made a few unprofessional comments about pledging that she had heard about (having to pull all-nighters in the library, never sleeping, etc that I am guessing she heard from other brothers so not holding it too much against her). In general though hard to talk to, I had to push a conversation along. Could be shyness, but came off as though she was uninterested.',
    'encounters': {'pre_t50': true, 'speed_dating': false, 't50': true},
    'weight': 50},
   {'brother_id': '5d83e931a051ef6e3d9f992c',
    'professional_score': 6,
    'social_score': 6,
    'comment': '',
    'encounters': {'pre_t50': false, 'speed_dating': false, 't50': false},
    'weight': 50}],
  'gi': [{'brother_name': 'John Gearig',
    'score': 12,
    'decision': 'No w/ Reserves',
    'comments': '-logical and non-dominant\n-decent communicating'},
   {'brother_name': 'Annika',
    'score': 8,
    'decision': 'No',
    'comments': "-writing on board not really adding ideas or commentary\n-not a lot of enthusiasm in her presentation\n-wasn't looking at others while they spoke"}],
  'ii': [{'brother_name': 'Audrey Humphrey ',
    'score': 12.75,
    'decision': 'Yes w/ Reserves',
    'comments': '-yes with reserves but could be no with reserves, v on the fence\n-got better at the end when she apoke about her aerospace engineering interests, through her overall tone was  monotone, and she had to be pressed on most questions'},
   {'brother_name': 'Sinan Karabocuoglu',
    'score': 14.25,
    'decision': 'Yes w/ Reserves',
    'comments': "-she is very interestedin the field and knowledgable\n-she was a monotone and doesn't try hard on challenging questions\n-she didnt ask any questions at the end "},
   {'brother_name': 'Arjun Vivek',
    'score': 12.5,
    'decision': 'Yes w/ Reserves',
    'comments': 'LACKS CONFIDENCE AND EXPERIENE\n\n-Unique way of thinking'}],
  'vm2': {'curr_rank': 2, 'locked': false, 'strike': false}}]