export const rusheeList = [{'name': 'Ashish Mahuli',
'id': 'AshishMahuli2',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 4.4,
 'rr': 2.6,
 'ii': 9.5,
 'gi': 9.0,
 'total': 6.8,
 'curr_rank': 1,
 'calc_rank': 1}},

{'name': 'Nick Huang',
'id': 'NickHuang2',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 0.3,
 'rr': 2.8,
 'ii': 3.4,
 'gi': 7.5,
 'total': 3.1,
 'curr_rank': 47,
 'calc_rank': 47}}]
