export const rusheeList = [{'name': 'Gurish Sharma',
'id': 'Gurish Sharma0',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 4.4,
 'rr': 2.6,
 'ii': 9.5,
 'gi': 9.0,
 'total': 6.8,
 'curr_rank': 1,
 'calc_rank': 1}},
{'name': 'Isabelle Carpenter',
'id': 'Isabelle Carpenter1',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.5,
 'rr': 3.5,
 'ii': 9.3,
 'gi': 8.9,
 'total': 6.46,
 'curr_rank': 2,
 'calc_rank': 2}},
{'name': 'Sachin Kurapati',
'id': 'Sachin Kurapati2',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.9,
 'rr': 2.5,
 'ii': 9.1,
 'gi': 8.6,
 'total': 6.37,
 'curr_rank': 3,
 'calc_rank': 3}},
{'name': 'Sophia Papadopoulos',
'id': 'Sophia Papadopoulos3',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 4.4,
 'rr': 3.8,
 'ii': 8.4,
 'gi': 7.3,
 'total': 6.19,
 'curr_rank': 4,
 'calc_rank': 4}},
{'name': 'Lara Mathias',
'id': 'Lara Mathias4',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.8,
 'rr': 5.5,
 'ii': 9.3,
 'gi': 6.4,
 'total': 6.17,
 'curr_rank': 5,
 'calc_rank': 5}},
{'name': 'Zach Philllips',
'id': 'Zach Philllips5',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 4.5,
 'rr': 2.7,
 'ii': 7.9,
 'gi': 7.9,
 'total': 6.11,
 'curr_rank': 6,
 'calc_rank': 6}},
{'name': 'Dylan Schwartz',
'id': 'Dylan Schwartz6',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 4.1,
 'rr': 1.7,
 'ii': 8.6,
 'gi': 7.9,
 'total': 6.04,
 'curr_rank': 7,
 'calc_rank': 7}},
{'name': 'Leon Maksin',
'id': 'Leon Maksin7',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 4.6,
 'rr': 6.9,
 'ii': 8.0,
 'gi': 5.2,
 'total': 5.97,
 'curr_rank': 8,
 'calc_rank': 8}},
{'name': 'Vineet Raju',
'id': 'Vineet Raju8',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.3,
 'rr': 3.6,
 'ii': 7.8,
 'gi': 8.7,
 'total': 5.89,
 'curr_rank': 9,
 'calc_rank': 9}},
{'name': 'Rita Vega',
'id': 'Rita Vega9',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 4.0,
 'rr': 3.6,
 'ii': 7.1,
 'gi': 8.3,
 'total': 5.87,
 'curr_rank': 10,
 'calc_rank': 10}},
{'name': 'Marina Sun',
'id': 'Marina Sun10',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.4,
 'rr': 1.8,
 'ii': 9.2,
 'gi': 7.3,
 'total': 5.86,
 'curr_rank': 11,
 'calc_rank': 11}},
{'name': 'Bobbi Scott',
'id': 'Bobbi Scott11',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.0,
 'rr': 0.9,
 'ii': 8.5,
 'gi': 8.2,
 'total': 5.62,
 'curr_rank': 12,
 'calc_rank': 12}},
{'name': 'Sachin Advani',
'id': 'Sachin Advani12',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.9,
 'rr': 2.1,
 'ii': 8.0,
 'gi': 8.4,
 'total': 5.6,
 'curr_rank': 13,
 'calc_rank': 13}},
{'name': 'Eric Jaimes',
'id': 'Eric Jaimes13',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.9,
 'rr': 2.7,
 'ii': 7.4,
 'gi': 6.1,
 'total': 5.32,
 'curr_rank': 14,
 'calc_rank': 14}},
{'name': 'Logan Roach',
'id': 'Logan Roach14',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.0,
 'rr': 3.1,
 'ii': 7.8,
 'gi': 6.2,
 'total': 5.19,
 'curr_rank': 15,
 'calc_rank': 15}},
{'name': 'Ian Fischer',
'id': 'Ian Fischer15',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.5,
 'rr': 1.8,
 'ii': 6.3,
 'gi': 8.0,
 'total': 5.16,
 'curr_rank': 16,
 'calc_rank': 16}},
{'name': 'Eleanor Markus',
'id': 'Eleanor Markus16',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.5,
 'rr': 1.4,
 'ii': 6.9,
 'gi': 8.8,
 'total': 5.15,
 'curr_rank': 17,
 'calc_rank': 17}},
{'name': 'Bright Xu',
'id': 'Bright Xu17',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.6,
 'rr': 4.4,
 'ii': 6.4,
 'gi': 8.0,
 'total': 5.13,
 'curr_rank': 18,
 'calc_rank': 18}},
{'name': 'Natasha Singhvi',
'id': 'Natasha Singhvi18',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.1,
 'rr': 3.3,
 'ii': 6.5,
 'gi': 9.1,
 'total': 5.11,
 'curr_rank': 19,
 'calc_rank': 19}},
{'name': 'Budnyam Galbadrakh',
'id': 'Budnyam Galbadrakh19',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.4,
 'rr': 2.6,
 'ii': 5.7,
 'gi': 8.2,
 'total': 5.08,
 'curr_rank': 20,
 'calc_rank': 20}},
{'name': 'Rania Uppal',
'id': 'Rania Uppal20',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.3,
 'rr': 1.9,
 'ii': 7.0,
 'gi': 6.6,
 'total': 5.03,
 'curr_rank': 21,
 'calc_rank': 21}},
{'name': 'Aiyana Chopra',
'id': 'Aiyana Chopra21',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.6,
 'rr': 1.8,
 'ii': 6.2,
 'gi': 8.8,
 'total': 5.0,
 'curr_rank': 22,
 'calc_rank': 22}},
{'name': 'Alice Gabidoulline',
'id': 'Alice Gabidoulline22',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.6,
 'rr': 4.0,
 'ii': 7.8,
 'gi': 7.4,
 'total': 4.99,
 'curr_rank': 23,
 'calc_rank': 23}},
{'name': 'Ryan Frank',
'id': 'Ryan Frank23',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.1,
 'rr': 1.7,
 'ii': 6.9,
 'gi': 8.7,
 'total': 4.99,
 'curr_rank': 24,
 'calc_rank': 24}},
{'name': 'Sophie Park',
'id': 'Sophie Park24',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.1,
 'rr': 2.9,
 'ii': 6.6,
 'gi': 8.3,
 'total': 4.92,
 'curr_rank': 25,
 'calc_rank': 25}},
{'name': 'Omar Elrashid',
'id': 'Omar Elrashid25',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.8,
 'rr': 1.2,
 'ii': 7.8,
 'gi': 6.1,
 'total': 4.85,
 'curr_rank': 26,
 'calc_rank': 26}},
{'name': 'Charles Weissman',
'id': 'Charles Weissman26',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.5,
 'rr': 1.1,
 'ii': 8.5,
 'gi': 7.0,
 'total': 4.79,
 'curr_rank': 27,
 'calc_rank': 27}},
{'name': 'Milin Macha',
'id': 'Milin Macha27',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.5,
 'rr': 2.5,
 'ii': 5.8,
 'gi': 7.9,
 'total': 4.71,
 'curr_rank': 28,
 'calc_rank': 28}},
{'name': 'Dhruv Thakkar',
'id': 'Dhruv Thakkar28',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.6,
 'rr': 3.6,
 'ii': 6.8,
 'gi': 7.7,
 'total': 4.71,
 'curr_rank': 29,
 'calc_rank': 29}},
{'name': 'Ali Eter',
'id': 'Ali Eter29',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.9,
 'rr': 1.8,
 'ii': 6.7,
 'gi': 8.0,
 'total': 4.69,
 'curr_rank': 30,
 'calc_rank': 30}},
{'name': 'Katherine Sturrock',
'id': 'Katherine Sturrock30',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.2,
 'rr': 1.9,
 'ii': 6.1,
 'gi': 8.2,
 'total': 4.69,
 'curr_rank': 31,
 'calc_rank': 31}},
{'name': 'An-Hung (Spencer) Nguyen',
'id': 'An-Hung (Spencer) Nguyen31',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.8,
 'rr': 2.9,
 'ii': 3.8,
 'gi': 8.1,
 'total': 4.68,
 'curr_rank': 32,
 'calc_rank': 32}},
{'name': 'Grace Maloney',
'id': 'Grace Maloney32',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.9,
 'rr': 5.0,
 'ii': 7.0,
 'gi': 5.8,
 'total': 4.64,
 'curr_rank': 33,
 'calc_rank': 33}},
{'name': 'Joshua Siegel',
'id': 'Joshua Siegel33',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 3.6,
 'rr': 1.3,
 'ii': 4.8,
 'gi': 7.6,
 'total': 4.61,
 'curr_rank': 34,
 'calc_rank': 34}},
{'name': 'Neha Subrahmanyam',
'id': 'Neha Subrahmanyam34',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.8,
 'rr': 2.5,
 'ii': 4.9,
 'gi': 8.0,
 'total': 4.59,
 'curr_rank': 35,
 'calc_rank': 35}},
{'name': 'Berrak Erata',
'id': 'Berrak Erata35',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.0,
 'rr': 3.7,
 'ii': 5.8,
 'gi': 7.4,
 'total': 4.51,
 'curr_rank': 36,
 'calc_rank': 36}},
{'name': 'Nathan Reichenbach',
'id': 'Nathan Reichenbach36',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.1,
 'rr': 2.1,
 'ii': 5.5,
 'gi': 8.3,
 'total': 4.5,
 'curr_rank': 37,
 'calc_rank': 37}},
{'name': 'Ishan Goel',
'id': 'Ishan Goel37',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.8,
 'rr': 2.8,
 'ii': 6.2,
 'gi': 7.5,
 'total': 4.5,
 'curr_rank': 38,
 'calc_rank': 38}},
{'name': 'Caroline Cisneros',
'id': 'Caroline Cisneros38',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.0,
 'rr': 2.0,
 'ii': 5.7,
 'gi': 8.0,
 'total': 4.47,
 'curr_rank': 39,
 'calc_rank': 39}},
{'name': 'Kostadina (Koko) Makrygiannis',
'id': 'Kostadina (Koko) Makrygiannis39',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.1,
 'rr': 1.7,
 'ii': 5.4,
 'gi': 7.8,
 'total': 4.35,
 'curr_rank': 40,
 'calc_rank': 40}},
{'name': 'Oliver Burnstein',
'id': 'Oliver Burnstein40',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.8,
 'rr': 2.5,
 'ii': 4.8,
 'gi': 8.4,
 'total': 4.29,
 'curr_rank': 41,
 'calc_rank': 41}},
{'name': 'Sonali Pai',
'id': 'Sonali Pai41',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.1,
 'rr': 2.5,
 'ii': 6.1,
 'gi': 7.7,
 'total': 4.19,
 'curr_rank': 42,
 'calc_rank': 42}},
{'name': 'Luke Polyak',
'id': 'Luke Polyak42',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.3,
 'rr': 1.7,
 'ii': 4.8,
 'gi': 8.7,
 'total': 4.06,
 'curr_rank': 43,
 'calc_rank': 43}},
{'name': 'Aaron Santilli',
'id': 'Aaron Santilli43',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 2.7,
 'rr': 0.5,
 'ii': 3.6,
 'gi': 8.5,
 'total': 4.03,
 'curr_rank': 44,
 'calc_rank': 44}},
{'name': 'Athena Ding',
'id': 'Athena Ding44',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 1.0,
 'rr': 3.5,
 'ii': 5.3,
 'gi': 6.8,
 'total': 3.83,
 'curr_rank': 45,
 'calc_rank': 45}},
{'name': 'Jetal Patel',
'id': 'Jetal Patel45',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 0.1,
 'rr': 1.5,
 'ii': 5.5,
 'gi': 7.9,
 'total': 3.63,
 'curr_rank': 46,
 'calc_rank': 46}},
{'name': 'Oliver Wang',
'id': 'Oliver Wang46',
'vm2': {'locked': false,
 'strike': false,
 'bhs': 0.3,
 'rr': 2.8,
 'ii': 3.4,
 'gi': 7.5,
 'total': 3.1,
 'curr_rank': 47,
 'calc_rank': 47}}]